Use attributes values_for_database instead of the casted value when c…
Beyond-Finance/active_force pull request #33
Opened 2023-04-14 14:25 UTC by stevenskim

…ommitting to SF

https://github.com/Beyond-Finance/active_force/issues/32

2023-04-14 14:27 UTC, stevenskim commented on lib/active_force/sobject.rb
> +      attrs = self.class.mapping.translate_to_sf(@attributes.values_for_database.slice(*changed))
Since `modified_attributes` was a public method, I didn't want to change it's behavior.

2023-04-14 14:29 UTC, stevenskim commented on lib/active_model/type/salesforce/multipicklist.rb
> +          value.to_s.split(';')
Set is probably a better representation of Multiselect Picklist, but I thought it would be better not to change it to prevent any negative outcome.

2023-04-14 14:33 UTC, stevenskim commented on lib/active_model/type/salesforce/multipicklist.rb
> +        include ActiveModel::Type::Helpers::Mutable
This fixes a bug where if you mutate an existing array, it won't catch that it changed if you were to save the record.  You would've have to set new array in order for the change value to be picked up.

2023-04-14 16:20 UTC, JeffLuckett requested changes
Could you add a test(s) that demonstrate/validate the new behavior?

2023-04-14 16:58 UTC, stevenskim commented
@JeffLuckett  Following already does the multipicklist tests.  I've added a test that it detects the mutation of an Array on `multipicklist` which I believe is the only difference in behavior.  Is there any other specific test(s) you would like see?

https://github.com/Beyond-Finance/active_force/blob/main/spec/active_force/sobject_spec.rb#L68-L94

[The base implementation of `serialize`](https://github.com/rails/rails/blob/main/activemodel/lib/active_model/type/value.rb#L59-L65) is to return the same casted value, so existing types should not change in it's behavior.

2023-04-14 17:53 UTC, JeffLuckett approved these changes

2023-04-14 19:30 UTC, stevenskim commented
do-not-merge:  Leads Service will push this change out to Production first to give it some sanity check.  Afterwards, I'll go ahead and take the necessary steps to get this merged and out in Glue.

2023-04-18 18:05 UTC, JeffLuckett requested changes

2023-04-18 18:05 UTC, JeffLuckett commented on CHANGELOG.md
> +## 0.11.5
We've just made a 0.12.0 release, so please update before you merge

2023-04-18 18:05 UTC, JeffLuckett commented on lib/active_force/version.rb
> +  VERSION = '0.11.5'
This will be `0.12.x`

2023-04-25 17:12 UTC, stevenskim commented
Updated version to 0.12.1

2023-04-25 18:16 UTC, JeffLuckett approved these changes

2023-04-28 19:58 UTC, asedge commented on lib/active_model/type/salesforce/multipicklist.rb
> +ActiveModel::Type.register(:multipicklist, ActiveModel::Type::Salesforce::Multipicklist)
Has this typo been in the gem the whole time?!?!

2023-04-28 20:17 UTC, asedge commented
@stevenskim Could you resolve the conflict?  You can throw your change under the `not released` section of the CHANGELOG so we can batch a few changes up before cutting a release.

2023-05-03 16:32 UTC, merged